### ISSUE TITLE
Import error for sphinx-markdown-tables

### ISSUE THREAD

**Issue by wilsonyou** [ryanfox/sphinx-markdown-tables#11]
Hi,

As you suggested, I added the extension sphinx_markdown_tables to the conf.py.

But when i tried to build the doc on readthedocs, the following errors were displayed.

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/hopeone/envs/master/lib/python3.5/site-packages/sphinx/registry.py", line 315, in load_extension
    mod = __import__(extname, None, None, ['setup'])
ImportError: No module named 'sphinx_markdown_tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/hopeone/envs/master/lib/python3.5/site-packages/sphinx/cmdline.py", line 303, in main
    args.warningiserror, args.tags, args.verbosity, args.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/hopeone/envs/master/lib/python3.5/site-packages/sphinx/application.py", line 191, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/hopeone/envs/master/lib/python3.5/site-packages/sphinx/application.py", line 411, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/hopeone/envs/master/lib/python3.5/site-packages/sphinx/registry.py", line 318, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname, err)
sphinx.errors.ExtensionError: Could not import extension sphinx_markdown_tables (exception: No module named 'sphinx_markdown_tables')

Extension error:
Could not import extension sphinx_markdown_tables (exception: No module named 'sphinx_markdown_tables')

**Comment by omad** [comment]
The `sphinx_markdown_tables` package isn't installed on RTD automatically. You need to specify it as a build requirement. See [Specifying Dependencies in the RTD Docs](https://docs.readthedocs.io/en/latest/guides/specifying-dependencies.html) for information about how.

It's probably as simple as creating a `requirements.txt` file in the base directory of your docs, with the contents:

    sphinx_markdown_tables

**Comment by wilsonyou** [comment]
@omad Thank you.

But I don't know how to configure the setup.py which is required when you use the requirements.txt.

Could you help on this?

Thank you

**Comment by wilsonyou** [comment]
@ I copied the setup.py from your project but It did not work. Could you help on this?

**Comment by wilsonyou** [comment]
@omad  It seems that I do not need a setup.py.

Thank you for your help.

**Comment by ryanfox** [comment]
Closing as solved.
