### ISSUE TITLE
Error using sphinx-markdown-tables 

### ISSUE THREAD

**Issue by aborruso** [ryanfox/sphinx-markdown-tables#12]
Hi,
I'm not able to compile again [this](https://readthedocs.org/projects/hfcqgis/) website based on [this repo](https://github.com/gbvitrano/HfcQGIS) with these [requirements](https://github.com/gbvitrano/HfcQGIS/blob/master/requirements.txt).

I the error below.

Some ideas on how to solve it?

Thank you

```
Collecting markdown (from -r /home/docs/checkouts/readthedocs.org/user_builds/hfcqgis/checkouts/latest/requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/6d/7d/488b90f470b96531a3f5788cf12a93332f543dbab13c423a5e7ce96a0493/Markdown-2.6.11-py2.py3-none-any.whl (78kB)
Collecting sphinx-markdown-tables (from -r /home/docs/checkouts/readthedocs.org/user_builds/hfcqgis/checkouts/latest/requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/fc/6e/586cfd5dda9ab7d40476332d1f8e74499e3f1cb5c4d245a81787fce42f59/sphinx-markdown-tables-0.0.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-hPJuTs/sphinx-markdown-tables/setup.py", line 5, in <module>
        from sphinx_markdown_tables import __version__
      File "sphinx_markdown_tables/__init__.py", line 3, in <module>
        import markdown
    ImportError: No module named markdown
```

**Comment by omad** [comment]
Looks like it's passing now. Well done.

(probably safe to close this issue now?)

**Comment by aborruso** [comment]
Now we use python 3 and it works. Not with 2.7
